import com.huacainfo.ace.common.tools.JsonUtil;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.converters.Converter;
import com.thoughtworks.xstream.converters.MarshallingContext;
import com.thoughtworks.xstream.converters.UnmarshallingContext;
import com.thoughtworks.xstream.io.HierarchicalStreamReader;
import com.thoughtworks.xstream.io.HierarchicalStreamWriter;
import org.dom4j.*;
import org.junit.Test;

import java.util.*;

/**
 * Created by Arvin on 2018/2/6.
 */
public class ConvertUtil {

    public ConvertUtil() {
    }

    @Test
    public void test() {

        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?><table>\n" +
                "<head>\n" +
                "<result result_code=\"0\" message=\"成功\" size=\"32\" />\n" +
                "</head>\n" +
                "<rows>\n" +
                "<row i_id=\"1\" c_classname=\"Domain\" c_org_name=\"常德市\" i_parent_id=\"null\" c_org_code=\"init-domain\" c_index_code=\"001067\" c_org_desc=\"初始化的域\" i_operate_role_id=\"7\" i_config_role_id=\"6\" i_manage_role_id=\"5\" i_default_role_id=\"1\" c_path=\",1,\" c_area_code=\"001067\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2013-10-29 14:27:06\" c_update_time=\"2018-01-30 17:35:46\" i_sys_role_id=\"2\" i_safe_role_id=\"3\" i_audit_role_id=\"4\" i_org_tree_id=\"null\" i_order=\"0\" i_level=\"1\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"null\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"cds\" createtime=\"2013-10-29 14:27:06\" pinyincode=\"cds\" creator=\"1\" parentid=\"null\" order=\"0\" orgcode=\"init-domain\" path=\",1,\" classname=\"Domain\" cascadecode=\"null\" updatetime=\"2018-01-30 17:35:46\" status=\"0\" areacode=\"001067\" orgname=\"常德市\" orgtreeid=\"null\" orgdesc=\"初始化的域\" orginternalcode=\"001067\"  />\n" +
                "<row i_id=\"3\" c_classname=\"Organization\" c_org_name=\"武陵区\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001068\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"9\" c_path=\",1,3,\" c_area_code=\"001068\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-01-30 17:35:58\" c_update_time=\"2018-01-30 17:35:58\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"3\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"wlq\" createtime=\"2018-01-30 17:35:58\" pinyincode=\"wlq\" creator=\"1\" parentid=\"1\" order=\"1\" orgcode=\"null\" path=\",1,3,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-01-30 17:35:58\" status=\"0\" areacode=\"001068\" orgname=\"武陵区\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001068\"  />\n" +
                "<row i_id=\"4\" c_classname=\"Organization\" c_org_name=\"经开区\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001069\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"10\" c_path=\",1,4,\" c_area_code=\"001069\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-01-30 17:36:04\" c_update_time=\"2018-01-30 17:36:04\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"2\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"4\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"jkq\" createtime=\"2018-01-30 17:36:04\" pinyincode=\"jkq\" creator=\"1\" parentid=\"1\" order=\"2\" orgcode=\"null\" path=\",1,4,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-01-30 17:36:04\" status=\"0\" areacode=\"001069\" orgname=\"经开区\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001069\"  />\n" +
                "<row i_id=\"5\" c_classname=\"Organization\" c_org_name=\"桃源县\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001070\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"11\" c_path=\",1,5,\" c_area_code=\"001070\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-01-30 17:36:09\" c_update_time=\"2018-01-30 17:36:09\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"3\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"5\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"tyx\" createtime=\"2018-01-30 17:36:09\" pinyincode=\"tyx\" creator=\"1\" parentid=\"1\" order=\"3\" orgcode=\"null\" path=\",1,5,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-01-30 17:36:09\" status=\"0\" areacode=\"001070\" orgname=\"桃源县\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001070\"  />\n" +
                "<row i_id=\"8\" c_classname=\"Organization\" c_org_name=\"市智慧党建办\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001126\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"14\" c_path=\",1,8,\" c_area_code=\"001126\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-01-31 15:06:53\" c_update_time=\"2018-01-31 15:06:53\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"4\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"8\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"szhdjb\" createtime=\"2018-01-31 15:06:53\" pinyincode=\"szhdjb\" creator=\"1\" parentid=\"1\" order=\"4\" orgcode=\"null\" path=\",1,8,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-01-31 15:06:53\" status=\"0\" areacode=\"001126\" orgname=\"市智慧党建办\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001126\"  />\n" +
                "<row i_id=\"9\" c_classname=\"Organization\" c_org_name=\"测试点\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001136\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"18\" c_path=\",1,9,\" c_area_code=\"001136\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 09:48:49\" c_update_time=\"2018-02-01 09:48:49\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"5\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"9\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"csd\" createtime=\"2018-02-01 09:48:49\" pinyincode=\"csd\" creator=\"1\" parentid=\"1\" order=\"5\" orgcode=\"null\" path=\",1,9,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 09:48:49\" status=\"0\" areacode=\"001136\" orgname=\"测试点\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001136\"  />\n" +
                "<row i_id=\"14\" c_classname=\"Organization\" c_org_name=\"鼎城区\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001165\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"23\" c_path=\",1,14,\" c_area_code=\"001165\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 14:46:13\" c_update_time=\"2018-02-01 14:46:13\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"6\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"14\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"dcq\" createtime=\"2018-02-01 14:46:13\" pinyincode=\"dcq\" creator=\"1\" parentid=\"1\" order=\"6\" orgcode=\"null\" path=\",1,14,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 14:46:13\" status=\"0\" areacode=\"001165\" orgname=\"鼎城区\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001165\"  />\n" +
                "<row i_id=\"21\" c_classname=\"Organization\" c_org_name=\"临澧县\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001206\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"30\" c_path=\",1,21,\" c_area_code=\"001206\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 16:02:05\" c_update_time=\"2018-02-04 16:02:05\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"7\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"llx\" createtime=\"2018-02-04 16:02:05\" pinyincode=\"llx\" creator=\"1\" parentid=\"1\" order=\"7\" orgcode=\"null\" path=\",1,21,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 16:02:05\" status=\"0\" areacode=\"001206\" orgname=\"临澧县\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001206\"  />\n" +
                "<row i_id=\"29\" c_classname=\"Organization\" c_org_name=\"澧县\" i_parent_id=\"1\" c_org_code=\"null\" c_index_code=\"001233\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"39\" c_path=\",1,29,\" c_area_code=\"001233\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-05 16:13:39\" c_update_time=\"2018-02-05 16:13:39\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"8\" i_level=\"2\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"29\" i_level3=\"null\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"lx\" createtime=\"2018-02-05 16:13:39\" pinyincode=\"lx\" creator=\"1\" parentid=\"1\" order=\"8\" orgcode=\"null\" path=\",1,29,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-05 16:13:39\" status=\"0\" areacode=\"001233\" orgname=\"澧县\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001233\"  />\n" +
                "<row i_id=\"10\" c_classname=\"Organization\" c_org_name=\"芷兰街道\" i_parent_id=\"3\" c_org_code=\"null\" c_index_code=\"001148\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"19\" c_path=\",1,3,10,\" c_area_code=\"001148\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 11:09:23\" c_update_time=\"2018-02-01 11:09:23\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"3\" i_level3=\"10\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"zljd\" createtime=\"2018-02-01 11:09:23\" pinyincode=\"zljd\" creator=\"1\" parentid=\"3\" order=\"1\" orgcode=\"null\" path=\",1,3,10,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 11:09:23\" status=\"0\" areacode=\"001148\" orgname=\"芷兰街道\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001148\"  />\n" +
                "<row i_id=\"12\" c_classname=\"Organization\" c_org_name=\"河洑镇\" i_parent_id=\"3\" c_org_code=\"null\" c_index_code=\"001157\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"21\" c_path=\",1,3,12,\" c_area_code=\"001157\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 12:22:33\" c_update_time=\"2018-02-01 12:22:33\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"2\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"3\" i_level3=\"12\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"hfz\" createtime=\"2018-02-01 12:22:33\" pinyincode=\"hfz\" creator=\"1\" parentid=\"3\" order=\"2\" orgcode=\"null\" path=\",1,3,12,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 12:22:33\" status=\"0\" areacode=\"001157\" orgname=\"河洑镇\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001157\"  />\n" +
                "<row i_id=\"17\" c_classname=\"Organization\" c_org_name=\"剪市镇\" i_parent_id=\"5\" c_org_code=\"null\" c_index_code=\"001195\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"26\" c_path=\",1,5,17,\" c_area_code=\"001195\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-03 13:04:06\" c_update_time=\"2018-02-03 13:04:06\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"5\" i_level3=\"17\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"jsz\" createtime=\"2018-02-03 13:04:06\" pinyincode=\"jsz\" creator=\"1\" parentid=\"5\" order=\"1\" orgcode=\"null\" path=\",1,5,17,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-03 13:04:06\" status=\"0\" areacode=\"001195\" orgname=\"剪市镇\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001195\"  />\n" +
                "<row i_id=\"19\" c_classname=\"Organization\" c_org_name=\"枫树乡\" i_parent_id=\"5\" c_org_code=\"null\" c_index_code=\"001200\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"28\" c_path=\",1,5,19,\" c_area_code=\"001200\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 11:34:29\" c_update_time=\"2018-02-04 11:34:29\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"2\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"5\" i_level3=\"19\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"fsx\" createtime=\"2018-02-04 11:34:29\" pinyincode=\"fsx\" creator=\"1\" parentid=\"5\" order=\"2\" orgcode=\"null\" path=\",1,5,19,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 11:34:29\" status=\"0\" areacode=\"001200\" orgname=\"枫树乡\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001200\"  />\n" +
                "<row i_id=\"11\" c_classname=\"Organization\" c_org_name=\"沙河社区\" i_parent_id=\"10\" c_org_code=\"null\" c_index_code=\"001152\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"20\" c_path=\",1,3,10,11,\" c_area_code=\"001152\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 11:20:07\" c_update_time=\"2018-02-01 11:20:07\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"3\" i_level3=\"10\" i_level4=\"11\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"shsq\" createtime=\"2018-02-01 11:20:07\" pinyincode=\"shsq\" creator=\"1\" parentid=\"10\" order=\"1\" orgcode=\"null\" path=\",1,3,10,11,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 11:20:07\" status=\"0\" areacode=\"001152\" orgname=\"沙河社区\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001152\"  />\n" +
                "<row i_id=\"13\" c_classname=\"Organization\" c_org_name=\"全美村\" i_parent_id=\"12\" c_org_code=\"null\" c_index_code=\"001158\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"22\" c_path=\",1,3,12,13,\" c_area_code=\"001158\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 12:22:43\" c_update_time=\"2018-02-01 12:22:43\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"3\" i_level3=\"12\" i_level4=\"13\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"qmc\" createtime=\"2018-02-01 12:22:43\" pinyincode=\"qmc\" creator=\"1\" parentid=\"12\" order=\"1\" orgcode=\"null\" path=\",1,3,12,13,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 12:22:43\" status=\"0\" areacode=\"001158\" orgname=\"全美村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001158\"  />\n" +
                "<row i_id=\"15\" c_classname=\"Organization\" c_org_name=\"草坪镇\" i_parent_id=\"14\" c_org_code=\"null\" c_index_code=\"001166\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"24\" c_path=\",1,14,15,\" c_area_code=\"001166\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 14:46:42\" c_update_time=\"2018-02-01 14:46:42\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"14\" i_level3=\"15\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"cpz\" createtime=\"2018-02-01 14:46:42\" pinyincode=\"cpz\" creator=\"1\" parentid=\"14\" order=\"1\" orgcode=\"null\" path=\",1,14,15,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 14:46:42\" status=\"0\" areacode=\"001166\" orgname=\"草坪镇\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001166\"  />\n" +
                "<row i_id=\"16\" c_classname=\"Organization\" c_org_name=\"枫林口村\" i_parent_id=\"15\" c_org_code=\"null\" c_index_code=\"001167\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"25\" c_path=\",1,14,15,16,\" c_area_code=\"001167\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-01 14:46:57\" c_update_time=\"2018-02-01 14:46:57\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"14\" i_level3=\"15\" i_level4=\"16\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"flkc\" createtime=\"2018-02-01 14:46:57\" pinyincode=\"flkc\" creator=\"1\" parentid=\"15\" order=\"1\" orgcode=\"null\" path=\",1,14,15,16,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-01 14:46:57\" status=\"0\" areacode=\"001167\" orgname=\"枫林口村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001167\"  />\n" +
                "<row i_id=\"18\" c_classname=\"Organization\" c_org_name=\"十字路口村\" i_parent_id=\"17\" c_org_code=\"null\" c_index_code=\"001196\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"27\" c_path=\",1,5,17,18,\" c_area_code=\"001196\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-03 13:04:17\" c_update_time=\"2018-02-03 13:04:17\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"5\" i_level3=\"17\" i_level4=\"18\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"szlkc\" createtime=\"2018-02-03 13:04:17\" pinyincode=\"szlkc\" creator=\"1\" parentid=\"17\" order=\"1\" orgcode=\"null\" path=\",1,5,17,18,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-03 13:04:17\" status=\"0\" areacode=\"001196\" orgname=\"十字路口村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001196\"  />\n" +
                "<row i_id=\"20\" c_classname=\"Organization\" c_org_name=\"白洋河村\" i_parent_id=\"19\" c_org_code=\"null\" c_index_code=\"001201\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"29\" c_path=\",1,5,19,20,\" c_area_code=\"001201\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 11:35:00\" c_update_time=\"2018-02-04 11:35:00\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"5\" i_level3=\"19\" i_level4=\"20\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"byhc\" createtime=\"2018-02-04 11:35:00\" pinyincode=\"byhc\" creator=\"1\" parentid=\"19\" order=\"1\" orgcode=\"null\" path=\",1,5,19,20,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 11:35:00\" status=\"0\" areacode=\"001201\" orgname=\"白洋河村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001201\"  />\n" +
                "<row i_id=\"22\" c_classname=\"Organization\" c_org_name=\"佘市镇\" i_parent_id=\"21\" c_org_code=\"null\" c_index_code=\"001207\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"31\" c_path=\",1,21,22,\" c_area_code=\"001207\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 16:02:22\" c_update_time=\"2018-02-04 16:02:22\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"22\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"ssz\" createtime=\"2018-02-04 16:02:22\" pinyincode=\"ssz\" creator=\"1\" parentid=\"21\" order=\"1\" orgcode=\"null\" path=\",1,21,22,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 16:02:22\" status=\"0\" areacode=\"001207\" orgname=\"佘市镇\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001207\"  />\n" +
                "<row i_id=\"25\" c_classname=\"Organization\" c_org_name=\"四新岗镇\" i_parent_id=\"21\" c_org_code=\"null\" c_index_code=\"001219\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"34\" c_path=\",1,21,25,\" c_area_code=\"001219\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 20:02:41\" c_update_time=\"2018-02-04 20:02:41\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"2\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"25\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"sxgz\" createtime=\"2018-02-04 20:02:41\" pinyincode=\"sxgz\" creator=\"1\" parentid=\"21\" order=\"2\" orgcode=\"null\" path=\",1,21,25,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 20:02:41\" status=\"0\" areacode=\"001219\" orgname=\"四新岗镇\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001219\"  />\n" +
                "<row i_id=\"27\" c_classname=\"Organization\" c_org_name=\"修梅镇\" i_parent_id=\"21\" c_org_code=\"null\" c_index_code=\"001227\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"36\" c_path=\",1,21,27,\" c_area_code=\"001227\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-05 10:44:34\" c_update_time=\"2018-02-05 10:44:34\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"3\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"27\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"xmz\" createtime=\"2018-02-05 10:44:34\" pinyincode=\"xmz\" creator=\"1\" parentid=\"21\" order=\"3\" orgcode=\"null\" path=\",1,21,27,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-05 10:44:34\" status=\"0\" areacode=\"001227\" orgname=\"修梅镇\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001227\"  />\n" +
                "<row i_id=\"34\" c_classname=\"Organization\" c_org_name=\"新安镇\" i_parent_id=\"21\" c_org_code=\"null\" c_index_code=\"001246\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"44\" c_path=\",1,21,34,\" c_area_code=\"001246\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-06 09:05:13\" c_update_time=\"2018-02-06 09:05:13\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"4\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"34\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"xaz\" createtime=\"2018-02-06 09:05:13\" pinyincode=\"xaz\" creator=\"1\" parentid=\"21\" order=\"4\" orgcode=\"null\" path=\",1,21,34,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-06 09:05:13\" status=\"0\" areacode=\"001246\" orgname=\"新安镇\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001246\"  />\n" +
                "<row i_id=\"23\" c_classname=\"Organization\" c_org_name=\"殷家村\" i_parent_id=\"22\" c_org_code=\"null\" c_index_code=\"001208\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"32\" c_path=\",1,21,22,23,\" c_area_code=\"001208\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 16:02:37\" c_update_time=\"2018-02-04 16:02:37\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"22\" i_level4=\"23\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"yjc\" createtime=\"2018-02-04 16:02:37\" pinyincode=\"yjc\" creator=\"1\" parentid=\"22\" order=\"1\" orgcode=\"null\" path=\",1,21,22,23,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 16:02:37\" status=\"0\" areacode=\"001208\" orgname=\"殷家村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001208\"  />\n" +
                "<row i_id=\"24\" c_classname=\"Organization\" c_org_name=\"蒋家村\" i_parent_id=\"22\" c_org_code=\"null\" c_index_code=\"001213\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"33\" c_path=\",1,21,22,24,\" c_area_code=\"001213\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 16:23:57\" c_update_time=\"2018-02-04 16:23:57\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"2\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"22\" i_level4=\"24\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"jjc\" createtime=\"2018-02-04 16:23:57\" pinyincode=\"jjc\" creator=\"1\" parentid=\"22\" order=\"2\" orgcode=\"null\" path=\",1,21,22,24,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 16:23:57\" status=\"0\" areacode=\"001213\" orgname=\"蒋家村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001213\"  />\n" +
                "<row i_id=\"26\" c_classname=\"Organization\" c_org_name=\"久丰村\" i_parent_id=\"25\" c_org_code=\"null\" c_index_code=\"001220\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"35\" c_path=\",1,21,25,26,\" c_area_code=\"001220\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-04 20:03:10\" c_update_time=\"2018-02-04 20:03:10\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"25\" i_level4=\"26\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"jfc\" createtime=\"2018-02-04 20:03:10\" pinyincode=\"jfc\" creator=\"1\" parentid=\"25\" order=\"1\" orgcode=\"null\" path=\",1,21,25,26,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-04 20:03:10\" status=\"0\" areacode=\"001220\" orgname=\"久丰村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001220\"  />\n" +
                "<row i_id=\"28\" c_classname=\"Organization\" c_org_name=\"赵家巷村\" i_parent_id=\"27\" c_org_code=\"null\" c_index_code=\"001228\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"37\" c_path=\",1,21,27,28,\" c_area_code=\"001228\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-05 10:46:18\" c_update_time=\"2018-02-05 10:46:18\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"27\" i_level4=\"28\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"zjxc\" createtime=\"2018-02-05 10:46:18\" pinyincode=\"zjxc\" creator=\"1\" parentid=\"27\" order=\"1\" orgcode=\"null\" path=\",1,21,27,28,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-05 10:46:18\" status=\"0\" areacode=\"001228\" orgname=\"赵家巷村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001228\"  />\n" +
                "<row i_id=\"30\" c_classname=\"Organization\" c_org_name=\"城头山\" i_parent_id=\"29\" c_org_code=\"null\" c_index_code=\"001234\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"40\" c_path=\",1,29,30,\" c_area_code=\"001234\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-05 16:13:52\" c_update_time=\"2018-02-05 16:13:52\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"29\" i_level3=\"30\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"cts\" createtime=\"2018-02-05 16:13:52\" pinyincode=\"cts\" creator=\"1\" parentid=\"29\" order=\"1\" orgcode=\"null\" path=\",1,29,30,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-05 16:13:52\" status=\"0\" areacode=\"001234\" orgname=\"城头山\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001234\"  />\n" +
                "<row i_id=\"32\" c_classname=\"Organization\" c_org_name=\"澧浦街道\" i_parent_id=\"29\" c_org_code=\"null\" c_index_code=\"001240\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"42\" c_path=\",1,29,32,\" c_area_code=\"001240\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-05 17:28:27\" c_update_time=\"2018-02-05 17:28:27\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"2\" i_level=\"3\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"29\" i_level3=\"32\" i_level4=\"null\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"lpjd\" createtime=\"2018-02-05 17:28:27\" pinyincode=\"lpjd\" creator=\"1\" parentid=\"29\" order=\"2\" orgcode=\"null\" path=\",1,29,32,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-05 17:28:27\" status=\"0\" areacode=\"001240\" orgname=\"澧浦街道\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001240\"  />\n" +
                "<row i_id=\"31\" c_classname=\"Organization\" c_org_name=\"牌楼村\" i_parent_id=\"30\" c_org_code=\"null\" c_index_code=\"001235\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"41\" c_path=\",1,29,30,31,\" c_area_code=\"001235\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-05 16:14:02\" c_update_time=\"2018-02-05 16:14:02\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"29\" i_level3=\"30\" i_level4=\"31\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"plc\" createtime=\"2018-02-05 16:14:02\" pinyincode=\"plc\" creator=\"1\" parentid=\"30\" order=\"1\" orgcode=\"null\" path=\",1,29,30,31,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-05 16:14:02\" status=\"0\" areacode=\"001235\" orgname=\"牌楼村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001235\"  />\n" +
                "<row i_id=\"33\" c_classname=\"Organization\" c_org_name=\"羊古社区\" i_parent_id=\"32\" c_org_code=\"null\" c_index_code=\"001241\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"43\" c_path=\",1,29,32,33,\" c_area_code=\"001241\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-05 17:28:42\" c_update_time=\"2018-02-05 17:28:42\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"29\" i_level3=\"32\" i_level4=\"33\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"ygsq\" createtime=\"2018-02-05 17:28:42\" pinyincode=\"ygsq\" creator=\"1\" parentid=\"32\" order=\"1\" orgcode=\"null\" path=\",1,29,32,33,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-05 17:28:42\" status=\"0\" areacode=\"001241\" orgname=\"羊古社区\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001241\"  />\n" +
                "<row i_id=\"35\" c_classname=\"Organization\" c_org_name=\"古城村\" i_parent_id=\"34\" c_org_code=\"null\" c_index_code=\"001247\" c_org_desc=\"\" i_operate_role_id=\"null\" i_config_role_id=\"null\" i_manage_role_id=\"null\" i_default_role_id=\"45\" c_path=\",1,21,34,35,\" c_area_code=\"001247\" i_status=\"0\" c_creator=\"1\" c_create_time=\"2018-02-06 09:05:25\" c_update_time=\"2018-02-06 09:05:25\" i_sys_role_id=\"null\" i_safe_role_id=\"null\" i_audit_role_id=\"null\" i_org_tree_id=\"1\" i_order=\"1\" i_level=\"4\" i_domain_id=\"1\" i_level1=\"1\" i_level2=\"21\" i_level3=\"34\" i_level4=\"35\" i_level5=\"null\" i_level6=\"null\" i_level7=\"null\" i_level8=\"null\" i_level9=\"null\" i_level10=\"null\" i_important_prison=\"null\" c_third_system=\"null\" c_cascade_code=\"null\" c_pinyin_code=\"gcc\" createtime=\"2018-02-06 09:05:25\" pinyincode=\"gcc\" creator=\"1\" parentid=\"34\" order=\"1\" orgcode=\"null\" path=\",1,21,34,35,\" classname=\"Organization\" cascadecode=\"null\" updatetime=\"2018-02-06 09:05:25\" status=\"0\" areacode=\"001247\" orgname=\"古城村\" orgtreeid=\"1\" orgdesc=\"\" orginternalcode=\"001247\"  />\n" +
                "</rows>\n" +
                "</table>";
        parseXml(xml);
    }

    public void parseXml(String xmlStr) {
        // 读取并解析XML文档
        // SAXReader就是一个管道，用一个流的方式，把xml文件读出来
        //
        // SAXReader reader = new SAXReader(); //User.hbm.xml表示你要解析的xml文档
        // Document document = reader.read(new File("User.hbm.xml"));
        // 下面的是通过解析xml字符串的
        try {
            Document rotDoc = DocumentHelper.parseText(xmlStr); // 将字符串转为XML
            Element rootElement = rotDoc.getRootElement(); // 获取根节点

            //解析head部分
            Iterator headIterator = rootElement.elementIterator("head"); // 获取根节点下的子节点head
            Map<String, String> headAttr = new HashMap<>();
            // 遍历
            while (headIterator.hasNext()) {
                Element headElement = (Element) headIterator.next();

                Iterator resultIterator = headElement.elementIterator("result");
                while (resultIterator.hasNext()) {
                    Element resultElement = (Element) resultIterator.next();
                    for (int i = 0; i < resultElement.attributeCount(); i++) {
                        Attribute attr = resultElement.attribute(i);
                        headAttr.put(attr.getQualifiedName(), attr.getValue());
                    }
                }

            }

            //解析rows部分
            Iterator rowsIterator = rootElement.elementIterator("rows"); // 获取根节点下的子节点head
            List<Map<String, String>> rowsAttrList = new ArrayList<>();
            // 遍历
            while (rowsIterator.hasNext()) {
                Element element = (Element) rowsIterator.next();

                Iterator iterator = element.elementIterator("row");
                Map<String, String> map;
                while (iterator.hasNext()) {
                    map = new HashMap<>();
                    Element resultElement = (Element) iterator.next();
                    for (int i = 0; i < resultElement.attributeCount(); i++) {
                        Attribute attr = resultElement.attribute(i);
                        map.put(attr.getQualifiedName(), attr.getValue());
                    }

                    rowsAttrList.add(map);
                }
            }

            System.out.println("123");
        } catch (DocumentException e) {
            e.printStackTrace();
        }
    }


    public void demo() {
        String xml = "<result result_code=\"0\" message=\"成功\" size=\"32\" />";

        XStream xstream = new XStream();
        xstream.alias("result", String.class);
        final Map<String, String> attributes = new HashMap<>();

        xstream.registerConverter(new Converter() {
            @Override
            public void marshal(Object source, HierarchicalStreamWriter writer, MarshallingContext context) {

            }

            @Override
            public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext context) {

                String attrName;
                String attrValue;
                for (int i = 0; i < reader.getAttributeCount(); i++) {
                    attrName = reader.getAttributeName(i);
                    attrValue = reader.getAttribute(i);
                    attributes.put(attrName, attrValue);
                }

                return true;
            }

            @Override
            public boolean canConvert(Class aClass) {

                return true;
            }
        });


        Object object = xstream.fromXML(xml);

        System.out.println(JsonUtil.toJson(object));
    }


}
